### ISSUE TITLE
Failed to set sensor

### ISSUE THREAD

**Issue by jenshorn** [vinnyspb/esphome-comfortzone#21]
The component has been running great for quite some time now, in particular reading the values. However I'm facing issues when trying to update/write any values to the CZ EX50.

When enabling fireplace mode: `[E][ComfortzoneComponent:653]: Fireplace mode: 1 FAILED`
Trying to set sensor offset: `Failed to set sensor 0 offset to 5.000000`

Nothing else in the logs when set to DEBUG mode. Hardware is S2 mini and the same RS485 linked in the readme.

Any ideas what might cause this?

Excerpt from yaml, pretty much the same as `configuration.yaml` in readme, just changed the pins somewhat:
```
substitutions:
  tx_pin: "39"
  rx_pin: "37"
  re_de_pin: "35"
  comfortzone_protocol_version: "180"

esp32:
  board: lolin_s2_mini
  framework:
    type: esp-idf

logger:
  level: DEBUG
```
